version: "3.8"
services:
  tusd_server:
    image: tusproject/tusd:v2.3
    container_name: hf_pics_tusd
    restart: always
    command: -verbose -s3-bucket $S3_BUCKET -s3-endpoint $S3_ENDPOINT -behind-proxy -hooks-enabled-events pre-create,post-finish -hooks-http http://server:5000/tusd_notify
    networks:
      - caddy
    environment:
      - AWS_REGION=$AWS_REGION
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    labels:
      caddy: tusd.hopefest.co.uk
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.reverse_proxy.transport: "http"
      caddy.reverse_proxy.flush_interval: -1

  imgproxy:
    image: darthsim/imgproxy:latest
    container_name: hf_pics_imgproxy
    restart: always
    networks:
      - caddy
    environment:
      - IMGPROXY_KEY=$IMGPROXY_KEY
      - IMGPROXY_SALT=$IMGPROXY_SALT
    labels:
      caddy: imgproxy.hopefest.co.uk
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.reverse_proxy.transport: "http"

  server:
    image: ghcr.io/vija02/hopefest_pictures:main
    container_name: hf_pics_server
    restart: always
    volumes:
      - ./db:/app/db
    networks:
      - caddy
    environment:
      - NODE_ENV=production
      - IMG_BASE_PATH=$IMG_BASE_PATH
      - IMGPROXY_PATH=https://imgproxy.hopefest.co.uk
      - IMGPROXY_KEY=$IMGPROXY_KEY
      - IMGPROXY_SALT=$IMGPROXY_SALT
    labels:
      caddy: pics24.hopefest.co.uk
      caddy.reverse_proxy: "{{upstreams 5000}}"
      caddy.reverse_proxy.transport: "http"

networks:
  caddy:
    external: true
